### ISSUE TITLE
iOS example

### ISSUE THREAD

**Issue by TSkovsgaard** [JuulLabs/sensortag#11]
Hi it would be nice with an iOS example to get one started quickly.

**Comment by twyatt** [comment]
Apologies, I was not watching this repository (I've fixed that now) so I did not see this issue.
I agree, it would be great to have an iOS example. Unfortunately I don't have the bandwidth to work on that at the moment.
PRs are welcome, otherwise I hope to one day have some time to put up an iOS example.

**Comment by lgayozo** [comment]
Hi everyone,

I have the same problem :S, @TSkovsgaard you have any example for iOS?

**Comment by twyatt** [comment]
I'll try to find some time in the coming weeks to use Compose multiplatform to demo running SensorTag example app on iOS. 🤞

**Comment by twyatt** [comment]
Took a lot longer to get to this than I had originally anticipated, but I'm now actively working on this.
